data-path="/usr/app/data"

rpc-http-enabled=true
rpc-http-api=["ETH", "NET", "IBFT"]
rpc-http-port=8549

p2p-port=30307

host-allowlist=["*"]

rpc-http-cors-origins=["all"]

genesis-file="/usr/app/genesis.json"

min-gas-price=0