version: "3"
services:
  node:
    image: hyperledger/besu:latest
    container_name: "node-2"
    ports:
      - 8546:8547
    volumes:
      - .:/usr/app/
    command: --config-file=/usr/app/config.toml
volumes:
  .: